services:
  - type: web
    name: ai-summarizer
    environment: python
    buildCommand: |
      pip install -r requirements.txt
      python download_model.py
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TRANSFORMERS_CACHE
        value: "/tmp/.cache"
